spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.241.49:3306/dp_crm?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123abc

  data:
    redis:
      host: 101.37.241.49
      port: 6379
      password:  123zsq # 如果没有密码，可以不写或写成空字符串